# Change these first
owner: itmanguru # Your GitHub username
repo: itman-upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: ATT Gateway
    url: https://104.52.87.190
    __dangerous_insecure: true
  - name: Itman HQ WAN1
    url: https://itman-hq-wan1.itman.guru:10443/
    __dangerous__insecure: true
  - name: Itman HQ WAN2
    url: https://itman-hq-wan2.itman.guru:10443/
    __dangerous__insecure: true
  - name: Itman Branch WAN1 
    url: https://itman-branch-wan1:10443/
    __dangerous__insecure: true

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: 
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /itman-upptime
  logoUrl: https://raw.githubusercontent.com/itman-upptime/upptime/master/assets/fortinet.png
  name: ITMAN Industries Network Services Delivery
  introTitle: "**ITMAN Network** services status"
  introMessage: This is a service status page which uses **real-time** data to display service status.
  navbar:
    - title: Status
      href: /
    - title: ITMAN Network Services
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
